// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75GCnmwvARcDkCB6Ake_Bi966tZACEto',
    appId: '1:48723883272:web:0da32d8ab6fbdd8370e8bd',
    messagingSenderId: '48723883272',
    projectId: 'chat-technical-test-b78c8',
    authDomain: 'chat-technical-test-b78c8.firebaseapp.com',
    storageBucket: 'chat-technical-test-b78c8.firebasestorage.app',
    measurementId: 'G-1PTTM9VBXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM71IKGVoMZRaIYUDZMVluZLZLCLgYYsA',
    appId: '1:48723883272:android:cebb1ba1c47b080670e8bd',
    messagingSenderId: '48723883272',
    projectId: 'chat-technical-test-b78c8',
    storageBucket: 'chat-technical-test-b78c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVfvb1QNtpEmxXnknSEa-kRkd2Hh41OM',
    appId: '1:48723883272:ios:85654d47d966586d70e8bd',
    messagingSenderId: '48723883272',
    projectId: 'chat-technical-test-b78c8',
    storageBucket: 'chat-technical-test-b78c8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVfvb1QNtpEmxXnknSEa-kRkd2Hh41OM',
    appId: '1:48723883272:ios:85654d47d966586d70e8bd',
    messagingSenderId: '48723883272',
    projectId: 'chat-technical-test-b78c8',
    storageBucket: 'chat-technical-test-b78c8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB75GCnmwvARcDkCB6Ake_Bi966tZACEto',
    appId: '1:48723883272:web:15c3f1ccf0bf60e670e8bd',
    messagingSenderId: '48723883272',
    projectId: 'chat-technical-test-b78c8',
    authDomain: 'chat-technical-test-b78c8.firebaseapp.com',
    storageBucket: 'chat-technical-test-b78c8.firebasestorage.app',
    measurementId: 'G-8X3NN0MHG4',
  );
}
